### ISSUE TITLE
Emojis aren't filtered out in code blocks

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Tymoji#5]
Check [here](https://scratch.mit.edu/discuss/topic/197642/?page=1#post-1965602) to see, at the end of the post.

The smile appears in the code block even though it shouldn't. This can cause problems when trying to demonstrate or sharing code for the userscript.

**Comment by joker314** [comment]
That is going to be a bit tricky, because you can nest code blocks. Or you could piggy-back off Scratch and check how Scrach decided to style the area you are trying to insert an image

**Comment by joker314** [comment]
Yes, I think I know what you need to do: create a style sheet that renders images invisible within code sections. I'll make a PR if I can

**Comment by joker314** [comment]
No, instead cycle through all elements with class "code" and remove images from within

**Comment by Tymewalk** [comment]
@joker314 Why not cycle through all elements with class "code" and remove them from the lists "posts" and "sigs"?

**Comment by joker314** [comment]
That won't work because some people might have tymojis both in and outside code tags at the same time, and so you can't remove the entire post, but removing code tags would make them dissapear from the post. Why not implement something that goes through each post, finds code tags, removes the tymojis and sores their index. Then it replaces them back at the index after the replace command. I'll make a PR soon

**Comment by joker314** [comment]
Wait, the commented out code, what was the problem with it?

**Comment by joker314** [comment]
@Tymewalk I think I fixed it, check my PR!

**Comment by joker314** [comment]
I added a small for loop at the end!

**Comment by joker314** [comment]
So could somebody merge it?

**Comment by joker314** [comment]
Please

**Comment by Tymewalk** [comment]
This got merged and was fixed quite a while ago. Closing as such.
